In [5]:
import pandas as pd

df = pd.read_excel("transformed6.xlsx")
df = df.drop(['Vehicle 1 Trim', 'Engine Size', 'Engine Block', 'Auto In The Market: New', 'Auto In The Market: Used', 'Model 1', 'Engine Cylinders', 'Drive Type', 'Fuel Type', 'Make 1', 'Unnamed: 0'], axis=1)

In [6]:
df.columns

Index(['Dwelling Type', 'Person Marital Status', 'Number of Persons in LU',
       'Person Occupation', 'Children: Age 0-18 Version 3',
       'Estimated Current Loan-to-Value Ratio', 'Person Type',
       'Mosaic Global Household', 'Est. Household Income V5',
       'Person Education', 'BehaviorBank: Presence of Credit Card',
       'Vehicle Type', 'Household Composition',
       'Consumer View Profitability Score', 'Homeowner Probability Model'],
      dtype='object')

In [7]:
for col in df.columns:
    print(col)
    l1 = []
    l2 = []
    i = 0
    j = 0
    q = 1
    x = len(df[col].unique())
    if(x<=4):
        continue
    else:
        for i in range(0,len(df)):
            x = df.loc[i,col]
            if(j < 4):
                if(x in l1):
                    df.loc[i,col] = l2[l1.index(x)]
                else:    
                    l1.append(x)
                    l2.append(q)
                    df.loc[i,col] = q
                    q = q + 1
                    j = j + 1
            else:
                if(x == l1[0]):
                    df.loc[i,col] = l2[0]
                elif(x == l1[1]):
                    df.loc[i,col] = l2[1]
                elif(x == l1[2]):
                    df.loc[i,col] = l2[2]    
                else:
                    df.loc[i,col] = 4

Dwelling Type
Person Marital Status
Number of Persons in LU
Person Occupation
Children: Age 0-18 Version 3
Estimated Current Loan-to-Value Ratio
Person Type
Mosaic Global Household
Est. Household Income V5
Person Education
BehaviorBank: Presence of Credit Card
Vehicle Type
Household Composition
Consumer View Profitability Score
Homeowner Probability Model

In [8]:
df

,Dwelling Type,Person Marital Status,Number of Persons in LU,Person Occupation,Children: Age 0-18 Version 3,Estimated Current Loan-to-Value Ratio,Person Type,Mosaic Global Household,Est. Household Income V5,Person Education,BehaviorBank: Presence of Credit Card,Vehicle Type,Household Composition,Consumer View Profitability Score,Homeowner Probability Model
0,S,1,1,1,1Y,1,P,1,1,1,Y,CAR,1,1,1
1,S,2,2,2,1Y,2,P,2,2,2,Y,CAR,2,2,2
2,S,3,3,3,1Y,3,P,3,3,3,Y,CAR,3,3,3
3,S,4,4,4,1Y,4,E,4,4,4,Y,SUV,4,4,4
4,S,4,4,4,1Y,4,E,4,4,4,Y,TRUCK,1,4,1
5,S,4,4,4,1Y,4,E,4,4,4,Y,TRUCK,1,4,1
6,A,1,4,1,5N,4,P,4,1,4,Y,CAR,4,4,4
7,S,1,4,1,1Y,4,P,4,4,1,Y,TRUCK,1,4,1
8,S,1,4,1,1Y,4,P,4,4,1,Y,CAR,1,4,1
9,S,4,4,1,5N,4,P,4,4,4,U,SUV,4,4,1
10,S,4,4,1,5N,4,P,4,4,4,U,VAN,4,4,1
11,S,4,4,1,5N,4,P,4,4,4,U,SUV,4,4,1
12,A,4,1,4,5U,4,E,4,4,4,Y,CAR,4,4,4
13,S,4,4,4,5U,4,Y,4,1,4,Y,CAR,4,4,1
14,S,4,4,4,5U,4,Y,4,1,4,Y,TRUCK,4,4,1
15,S,4,4,4,5U,4,Y,4,1,4,Y,CAR,4,4,1
16,S,4,4,4,5U,4,Y,4,1,4,Y,CAR,4,4,1
17,S,4,4,4,5U,4,P,4,4,4,Y,CAR,4,4,1
18,A,1,4,1,5U,4,P,4,4,4,U,TRUCK,4,4,4
19,A,1,4,1,5U,4,P,4,4,4,U,CAR,4,4,4
20,A,4,4,1,5N,4,P,4,4,4,U,CAR,4,4,4
21,A,4,4,1,5N,4,P,4,4,4,U,CAR,4,4,4
22,A,4,4,1,1Y,4,O,1,4,4,Y,CAR,4,4,4
23,A,4,4,1,1Y,4,O,1,4,4,Y,CAR,4,4,4
24,A,4,4,1,1Y,4,O,1,4,4,Y,TRUCK,4,4,4
25,A,4,4,1,1Y,4,O,1,4,4,Y,CAR,4,4,4
26,S,1,4,1,1Y,4,P,4,1,4,Y,CAR,4,1,4
27,S,4,1,1,1Y,4,P,1,4,4,U,CAR,4,4,1
28,S,1,4,4,5N,4,P,4,4,4,Y,VAN,4,4,1
29,S,1,4,4,5N,4,P,4,4,4,Y,CAR,4,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9969,S,4,4,4,5N,4,P,1,4,4,Y,CAR,4,4,4
9970,S,4,4,4,5N,4,P,1,4,4,Y,CAR,4,4,4
9971,S,4,4,1,5Y,4,P,4,4,4,U,TRUCK,4,4,4
9972,S,4,4,1,5Y,4,P,4,4,4,U,SUV,4,4,4
9973,S,4,4,1,5Y,4,P,4,4,4,U,CAR,4,4,4
9974,S,4,4,1,5Y,4,P,4,4,4,U,CAR,4,4,4
9975,S,4,4,1,5Y,4,P,4,4,4,U,CAR,4,4,4
9976,S,4,4,1,5Y,4,P,4,4,4,U,CAR,4,4,4
9977,S,4,4,1,5Y,4,P,4,4,4,U,CAR,4,4,4
9978,A,4,4,1,5N,4,P,4,4,4,U,CAR,4,1,4
9979,A,4,4,1,5N,4,P,4,4,4,U,TRUCK,4,1,4
9980,A,4,4,1,5N,4,P,4,4,4,U,CAR,4,1,4
9981,S,4,4,1,5N,4,P,1,4,4,U,VAN,4,4,1
9982,S,1,4,4,1Y,4,P,4,4,4,Y,SUV,4,4,1
9983,S,1,4,4,1Y,4,P,4,4,4,Y,SUV,4,4,1
9984,S,4,1,4,1Y,4,P,1,4,4,U,CAR,4,4,1
9985,S,4,4,4,5Y,4,P,4,4,4,Y,SUV,4,1,1
9986,S,1,4,4,5N,4,P,4,4,4,Y,CAR,4,4,4
9987,S,1,4,4,5N,4,P,4,4,4,Y,CAR,4,4,4
9988,S,1,4,4,5N,4,P,4,4,4,Y,CAR,4,4,4
9989,S,1,4,4,5N,4,P,4,4,4,Y,CAR,4,4,4
9990,S,1,4,4,5N,4,P,4,4,4,Y,TRUCK,4,4,4
9991,S,1,4,4,5N,4,P,4,4,4,Y,SUV,4,4,4
9992,S,4,4,1,1Y,4,O,1,4,4,Y,TRUCK,4,4,4
9993,S,4,4,1,1Y,4,O,1,4,4,Y,CAR,4,4,4
9994,S,4,4,1,1Y,4,O,1,4,4,Y,CAR,4,4,4
9995,S,4,4,1,1Y,4,O,1,4,4,Y,SUV,4,4,4
9996,S,1,4,1,5Y,4,P,4,4,4,U,CAR,4,4,1
9997,S,1,4,1,5Y,4,P,4,4,4,U,CAR,4,4,1
9998,S,1,4,1,5Y,4,P,4,4,4,U,SUV,4,4,1

In [ ]:
df1

In [ ]:
len(df)